### PR TITLE
Sync changes from openzipkin/openzipkin.github.io

### PR DESCRIPTION
**Pull request by abesto**

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
build bust on

```
[2019-04-22T02:05:37.849Z] + git checkout asf-site

[2019-04-22T02:05:37.849Z] error: pathspec 'asf-site' did not match any file(s) known to git.

script returned exit code 1
```

**Review by codefromthecrypt — APPROVED** [review]
looks good on green

**Comment by abesto** [comment]
PR build on top of #2 passed, correctly skipping Publish step. Merging.

**Comment by abesto** [comment]
Happy to report that after some Git wrangling, the build at <https://builds.apache.org/view/Z/view/Zipkin/job/GH-incubator-zipkin/job/incubator-zipkin-website/job/master/8/console> successfully updated the site (see https://github.com/apache/incubator-zipkin-website/commit/339d065b306579a7fa10ca8493e401c0ea13bdb0). Verified the site actually picked up the changes within seconds, for example "Server extensions and choices" is now showing up in the side-bar. This _should_ mean that any future changes will also be automatically built and published.

**Pull request merged**
