### PR TITLE
fix: enables pulling of submodule.

### PR DESCRIPTION
**Pull request by jcchavezs**

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
just clicked "scan repository now" to get jenkins to test this commit...
Screen Shot 2019-04-30 at 8 12 58 AM

**Comment by codefromthecrypt** [comment]
sadly:

```
[2019-04-30T00:12:49.293Z] + git submodule update --init --recursive

[2019-04-30T00:12:49.293Z] Submodule 'zipkin-api' (git@github.com:apache/incubator-zipkin-api.git) registered for path 'zipkin-api'

[2019-04-30T00:12:49.293Z] Cloning into 'zipkin-api'...

[2019-04-30T00:12:49.924Z] Permission denied (publickey).

[2019-04-30T00:12:49.924Z] fatal: Could not read from remote repository.

[2019-04-30T00:12:49.924Z] 

[2019-04-30T00:12:49.924Z] Please make sure you have the correct access rights

[2019-04-30T00:12:49.924Z] and the repository exists.

[2019-04-30T00:12:49.924Z] fatal: clone of 'git@github.com:apache/incubator-zipkin-api.git' into submodule path 'zipkin-api' failed

[2019-04-30T00:12:50.697Z] Terminated
```

**Comment by jcchavezs** [comment]
@adriancole I don't have access to "scan repository now" :(

image

**Comment by codefromthecrypt** [comment]
not sure why you don't have access.. mind pinging INFRA on slack? https://the-asf.slack.com/messages/CBX4TSBQ8/

I clicked and now crossing fingers

**Comment by codefromthecrypt** [comment]
no dice

```
07:58:34  + git submodule update --init --recursive
07:58:34  Submodule 'zipkin-api' (https://github.com/apache/incubator-zipkin-website) registered for path 'zipkin-api'
07:58:34  Cloning into 'zipkin-api'...
07:58:37  fatal: reference is not a tree: f352ff4891889c6b39ca5f3d6a7674b195cd878b
07:58:37  Unable to checkout 'f352ff4891889c6b39ca5f3d6a7674b195cd878b' in submodule path 'zipkin-api'
```

**Comment by codefromthecrypt** [comment]
Thanks @abesto and @jcchavezs! will build master to try

**Pull request merged**
